// 2026-09-20 批次 C：B97/B96「日报的同一天判定」随容器时区翻转的锁
// 运行：node --test tests/regression-20260920c.test.js
//
// 缺陷（读代码确认，非推测）：`GET /api/daily` 用 `genDate.toDateString() === now.toDateString()`
// 判"今天已经有一期了"。toDateString() 读的是**容器本地**日历日，而 Vercel 容器是 UTC：
// runner 每早北京 00:32 写的那一期，其 UTC 日历日是**前一天**（16:32Z），
// 于是同一个北京日内再打开日报 → 判成"不是今天"→ 走补生成分支，同一天多插一行。
// 修法：两端都按**北京日历日**比（lib/time-window.beijingDateStr），与容器时区无关。
//
// ⚠️ 为什么不拿真实钟点跑：这个缺陷只在"北京日相同、UTC 日不同"时暴露，即北京时间 08:00~24:00；
// 拿 Date.now() 跑的话，凌晨执行夹具前提不成立，测试会绿着空跑。所以子进程里**钉住 Date.now**，
// 并断言夹具前提（UTC 日必须不同、北京日必须相同）。
//
// 上一轮 reviewer 判"这条锁恒过"：他的样本 generated_at 的北京日是 09-19，而"现在"的北京日已是
// 09-20 —— 两个样本本来就跨了北京日界，测的不是这个缺陷。本文件的对齐样本可复现：未修必红。
'use strict';
const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { runDriver } = require('./driver-runner');

const ROOT = path.join(__dirname, '..');
const read = (...p) => fs.readFileSync(path.join(ROOT, ...p), 'utf8');
// 惰性 require：F2P 要在**改前基线**上逐条点名报红。顶层 require 的话，基线上没有
// lib/time-window.js → 整个文件加载崩，用例名一个都不出现（13 条锁被误判成"抓不到 bug"）。
const tw = () => require('../lib/time-window');
const briefGuards = require('../lib/brief-guards');

const DAY = 86400e3;
// 钉住的"现在"＝北京今日 13:00；库里那一期＝北京今日 00:32（同一北京日、不同 UTC 日）
const FIXED_NOW = () => tw().beijingDayStartMs() + 13 * 3600e3;
const GENERATED_AT = () => new Date(tw().beijingDayStartMs() + 32 * 60e3).toISOString();

test('C0 夹具前提：同一北京日、不同 UTC 日（否则这条锁只是在原地打转）', () => {
  const { beijingDateStr, beijingNow } = tw();
  const nowMs = FIXED_NOW();
  const gen = GENERATED_AT();
  assert.equal(beijingDateStr(Date.parse(gen)), beijingDateStr(nowMs),
    '夹具失效：这一期与钉住的"现在"不在同一个北京日');
  assert.notEqual(gen.slice(0, 10), new Date(nowMs).toISOString().slice(0, 10),
    '夹具失效：UTC 日历日相同，未修的 toDateString 判定本来也不会翻转');
  // 夹具必须走"补生成"那条路才判得到：北京 13:00 已过 hour>=1 门槛，且这一期不能被 AI 新鲜度分支救下
  assert.ok(beijingNow(nowMs).getUTCHours() >= 1, '夹具失效：钉住的时刻还没过补生成门槛');
  assert.equal(briefGuards.isAiDailyReport({ stats: JSON.stringify({ totalItems: 0 }) }), false,
    '夹具失效：这一期被当成 AI 增强版，freshAi 分支会绕过"同一天"判定，测不到 B97');
});

// 云端 catch-all 的 /api/daily：子进程 + 临时文件库（零生产写入）+ 钉住 Date.now
function runCloudDaily(tz, evaded) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'b97-cloud-'));
  const dbFile = path.join(dir, 'b.db').replace(/\\/g, '/');
  const driver = path.join(ROOT, `.b97-cloud-${process.pid}.cjs`);
  const srcFile = path.join(ROOT, 'api', '[...slug].js');
  // 变异副本必须落在**原文件同一目录**：它的 `require('../lib/…')` 才解析得到（放进 os.tmpdir
  // 会让它加载失败，探针就变成"静默不红"——上一版 C3 正是这么假绿的）
  const tmpSrc = path.join(ROOT, 'api', `.__evaded-${process.pid}.js`);
  if (evaded) {
    const orig = fs.readFileSync(srcFile, 'utf8');
    const NOW = 'if (beijingDateStr(genDate.getTime()) === beijingDateStr() || freshAi) {';
    assert.ok(orig.includes(NOW), '变异注入锚定失败：B97 判定式已被改写');
    fs.writeFileSync(tmpSrc, orig.replace(NOW,
      'if (genDate.toDateString() === new Date(Date.now()).toDateString() || freshAi) {'));
    assert.notEqual(fs.readFileSync(tmpSrc, 'utf8'), orig, '变异注入未改动内容');
  }
  const target = evaded ? tmpSrc : srcFile;
  fs.writeFileSync(driver, `
    Date.now = () => ${FIXED_NOW()};
    process.env.TURSO_DATABASE_URL = 'file:' + ${JSON.stringify(dbFile)};
    process.env.TURSO_AUTH_TOKEN = '';
    const { ensureSchema, dbRun, dbGet, close } = require(${JSON.stringify(path.join(ROOT, 'lib', 'db.js'))});
    const handler = require(${JSON.stringify(target)});
    (async () => {
      await ensureSchema();
      await dbRun("INSERT INTO sources(type,name,url,enabled) VALUES('rss','B97 源','https://b97.example/f',1)");
      await dbRun('INSERT INTO daily_reports(generated_at,window_hours,sections,stats) VALUES(?,?,?,?)',
        ${JSON.stringify(GENERATED_AT())}, 24, JSON.stringify([{ id: 'c1', title: 'B97', items: [] }]),
        JSON.stringify({ totalItems: 0, candidates: 0 }));
      const before = Number((await dbGet('SELECT COUNT(*) c FROM daily_reports')).c);
      const res = { _body: null };
      res.setHeader = () => res; res.status = () => res; res.json = (b) => { res._body = b; return res; };
      await handler({ method: 'GET', url: '/api/daily', query: {}, headers: {} }, res);
      const after = Number((await dbGet('SELECT COUNT(*) c FROM daily_reports')).c);
      const b = res._body || {};
      const rep = b.report || b;
      console.log('OUT ' + JSON.stringify({
        before, after,
        autoGenerated: !!rep.autoGenerated,
        served: rep.generated_at || null,
        err: b.error || null,
        now: Date.now(),
      }));
      await close();
    })().catch((e) => { console.log('OUT ' + JSON.stringify({ err: e.message })); process.exitCode = 3; });
  `);
  try {
    const out = runDriver(driver, [],
      { env: { ...process.env, TZ: tz }, timeout: 180000, payloadRe: /^OUT /m });
    const m = /^OUT (.+)$/m.exec(out);
    assert.ok(m, `子进程没打印读数（TZ=${tz}）：\n${out.slice(-500)}`);
    return JSON.parse(m[1]);
  } catch (e) {
    // 只改写**子进程失败**这一类错误；断言本身的失败要原样抛出（否则把真红伪装成环境红）
    if (e.stdout === undefined && e.stderr === undefined && e.status === undefined) throw e;
    // 失败必须带两侧读数：`Command failed` 这种裸错误无法定性（B105 那族"子进程在退出阶段崩溃"
    // 就是靠状态码 + 尾行输出才判成 fail_flaky 的，坑 #53 第⑤条 / 坑 #41）。
    const tail = (s) => String(s || '').split('\n').filter(Boolean).slice(-6).join(' ⏎ ') || '(空)';
    throw new Error(`驱动子进程失败 TZ=${tz} status=${e.status} signal=${e.signal}\n  stdout: ${tail(e.stdout)}\n  stderr: ${tail(e.stderr)}`);
  } finally {
    try { fs.unlinkSync(driver); } catch { /* 已清 */ }
    // 变异副本落在 api/ 目录里（为了相对 require 能解析），必须删干净——否则会污染 W 类全目录扫描
    if (evaded) { try { fs.unlinkSync(tmpSrc); } catch { /* 已清 */ } }
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

test('C1 云端 /api/daily：北京 00:32 那一期在 TZ=UTC 下不得被判成"昨天"并重复生成', () => {
  const r = runCloudDaily('UTC');
  assert.ok(!r.err, `端点报错：${r.err}`);
  assert.equal(r.now, FIXED_NOW(), '钉时间未生效，读数不可信');
  assert.equal(r.autoGenerated, false,
    `同一个北京日被判成"不是今天"→ 又自动生成了一份（B97 原样）：${JSON.stringify(r)}`);
  assert.equal(r.after, r.before, `daily_reports 多插了一行（before=${r.before} after=${r.after}）`);
  assert.equal(r.served, GENERATED_AT(), '返回的不是库里那一期，说明走的是补生成分支');
});

test('C2 换到 TZ=Asia/Shanghai 结果必须完全一致（判定不许依赖容器时区）', () => {
  const utc = runCloudDaily('UTC');
  const sh = runCloudDaily('Asia/Shanghai');
  assert.ok(!utc.err && !sh.err, `${JSON.stringify([utc.err, sh.err])}`);
  assert.equal(utc.autoGenerated, sh.autoGenerated, '同一份数据两端 autoGenerated 不同 → 判定读的是容器时区');
  assert.equal(utc.served, sh.served, '两端返回的不是同一期');
  assert.equal(sh.after, sh.before, 'TZ=Asia/Shanghai 下也重复生成了一份');
});

test('C3 反向自证（坑 #50）：判定退回 toDateString 形态后，C1 必须变红', () => {
  // 区分两种红：**锁变红**（判据抓到了退化代码，是好事）与**探针坏了**（变异体加载不起来）。
  // 上一版把后者也算成功，等于"复制源文件到 tmp 打断相对 require"就能骗过自检。
  let reading = null;
  try {
    reading = runCloudDaily('UTC', true);
  } catch (e) {
    const msg = String(e && e.message || '');
    assert.fail(`变异体没能跑出读数（探针自身坏了，不是判据抓到退化）：${msg.split('\n')[0]}`);
  }
  assert.ok(!reading.err, `变异体端点报错，读数不可信：${reading.err}`);
  assert.ok(reading.autoGenerated === true || reading.after > reading.before,
    `退回 toDateString 判定后 C1 仍是绿的 → 这条锁判不到 B97：${JSON.stringify(reading)}`);
});

test('C4 手动重新生成的删除区间必须是北京日（B96：北京日期串拼 UTC 边界删不掉凌晨那期）', () => {
  const { stripComments } = require('../lib/src-spans');
  const { beijingDateStr } = tw();
  const code = stripComments(read('api', '[...slug].js'));
  // 全文件级判据：出现"日期串 + T00:00:00.000Z"当时刻用即红（B96 就是这个形态）
  assert.ok(!/T00:00:00\.000Z/.test(code), '又出现"日期串 + T00:00:00.000Z"当边界（B96 形态）');
  assert.ok(/beijingDayStartMs\(\)/.test(code), 'regenerate 的删除区间不再走北京日界');
  // 数值自证：凌晨那一期落在旧区间的**外面**，否则这条判据是空跑
  const gms = Date.parse(GENERATED_AT());
  assert.ok(gms >= FIXED_NOW() - 13 * 3600e3 && gms < FIXED_NOW() - 13 * 3600e3 + DAY,
    '新北京日区间没覆盖凌晨那一期');
  const oldStart = Date.parse(`${beijingDateStr(gms)}T00:00:00.000Z`); // 旧写法：北京日期串 + UTC 零点
  assert.ok(gms < oldStart,
    `夹具不够强：旧边界本来也能覆盖它（gms=${gms} oldStart=${oldStart}），数值判据空跑`);
});

// ── C5 前端筛选日历与服务端逐时刻对齐（B99 的浏览器那一侧）──
// 前端不能 require CJS 的 lib/time-window.js，所以它是另一份实现（web/src/beijing-date.mjs）。
// "另一份实现"必须有对端锁，否则两份迟早分叉 —— 这里**真的 import 那份 ESM 跑数**，不是比对文本。
test('C5 前端 beijing-date.mjs 与 lib/time-window 在同一批时刻上必须给出同一个日历', async () => {
  const { pathToFileURL } = require('url');
  const web = await import(pathToFileURL(path.join(ROOT, 'web', 'src', 'beijing-date.mjs')).href);
  const tw = require('../lib/time-window');
  assert.ok(typeof web.beijingDateStr === 'function' && typeof web.beijingWeekStartStr === 'function'
    && typeof web.beijingMonthStartStr === 'function', '前端那份的导出面变了，本锁要跟着改');
  const bad = [];
  // 覆盖 6 天 × 每 90 分钟（含北京 00:00/08:00 两个界），再加几个跨月/跨年整点
  const instants = [];
  for (let i = 0; i < 96; i++) instants.push(Date.parse('2026-09-16T00:00:00Z') + i * 90 * 60e3);
  for (const s of ['2025-12-31T15:30:00Z', '2026-01-01T15:59:00Z', '2026-02-28T15:30:00Z',
    '2026-03-01T16:00:00Z', '2026-06-30T15:59:59Z', '2026-09-19T15:59:59Z', '2026-09-19T16:00:00Z']) {
    instants.push(Date.parse(s));
  }
  for (const ms of instants) {
    if (web.beijingDateStr(ms) !== tw.beijingDateStr(ms)) {
      bad.push(`${new Date(ms).toISOString()}：前端 ${web.beijingDateStr(ms)} ≠ 服务端 ${tw.beijingDateStr(ms)}`);
    }
  }
  assert.ok(instants.length > 100, '样本太少，等于没比对');
  assert.deepStrictEqual(bad.slice(0, 5), [], '两份日历实现已经分叉：\n' + bad.join('\n'));
  // 周一/月首：必须是"该时刻所在北京日"回退到周一/1 号，且自身与 lib 的日界算子一致
  const wdOf = (ds) => { // 用 lib 的日界把日期串还原成北京 12:00 的星期
    const ms = Date.parse(`${ds}T00:00:00.000Z`) + tw.BJ_OFFSET_MS;
    return new Date(ms).getUTCDay();
  };
  for (const ms of instants) {
    const wk = web.beijingWeekStartStr(ms), mo = web.beijingMonthStartStr(ms);
    assert.equal(wdOf(wk), 1, `${new Date(ms).toISOString()} 的"本周一"不是周一：${wk}`);
    assert.ok(wk <= web.beijingDateStr(ms) && web.beijingDateStr(ms) <= new Date(Date.parse(wk) + 6 * 86400e3)
      .toISOString().slice(0, 10), `"本周一"不在该北京日所在的 7 天内：${wk} / ${web.beijingDateStr(ms)}`);
    assert.ok(mo.endsWith('-01') && mo.slice(0, 7) === web.beijingDateStr(ms).slice(0, 7),
      `"本月一日"与该北京日不同月：${mo} / ${web.beijingDateStr(ms)}`);
  }
  // 反向：前端那份若退回"浏览器本地/UTC 日历"，本锁必须变红（拿 UTC 日串当对照）
  const utcDay = (ms) => new Date(ms).toISOString().slice(0, 10);
  const diff = instants.filter((ms) => utcDay(ms) !== tw.beijingDateStr(ms)).length;
  assert.ok(diff > 12, `对照本身没有区分度（${diff}/${instants.length} 个时刻 UTC 日 ≠ 北京日）——C5 判据是空的`);
});

test('C6 前端确实把这份日历用在筛选参数上（不是造了个没人调的函数）', () => {
  const { stripComments } = require('../lib/src-spans');
  const code = stripComments(read('web', 'src', 'components', 'FilterPanel.jsx'));
  assert.ok(/from\s*['"]?\/\s*beijing-date\.mjs/.test(read('web', 'src', 'components', 'FilterPanel.jsx'))
    || /beijing-date\.mjs/.test(read('web', 'src', 'components', 'FilterPanel.jsx')),
    'FilterPanel 不再引用 beijing-date.mjs（日期预设又回到各算各的）');
  assert.ok(/preset === 'today'[\s\S]{0,80}beijingDateStr\(\)/.test(code),
    '"今天"预设没有走北京日历日');
  assert.ok(!/toISOString\(\)\.slice\(0,\s*10\)/.test(code),
    'FilterPanel 又用 toISOString().slice(0,10) 取日历日（那是 UTC 日，B99 形态）');
});
